version: "3.8"

services:
    neopark-server:
        build: . # Menggunakan Dockerfile di root
        container_name: neopark-parking-system
        ports:
            - "5000:5000"
        volumes:
            - ./logs:/app/logs # Untuk log aplikasi Flask
        environment:
            - PYTHONUNBUFFERED=1
            - FLASK_ENV=production
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:5000/health",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s
        networks:
            - neopark-network

    nginx:
        image: nginx:alpine
        container_name: neopark-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./Website:/usr/share/nginx/html/website
        depends_on:
            - neopark-server
        restart: unless-stopped
        networks:
            - neopark-network

    prometheus:
        image: prom/prometheus:v2.51.0
        container_name: neopark-prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--web.enable-lifecycle"
            - "--log.level=debug" # Tambahkan untuk debugging
        restart: unless-stopped
        depends_on:
            - neopark-server
        networks:
            - neopark-network

    grafana:
        image: grafana/grafana:10.4.2
        container_name: neopark-grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin123 # Password yang lebih kuat
            - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        depends_on:
            - prometheus
        networks:
            - neopark-network

networks:
    neopark-network:
        driver: bridge

volumes:
    logs:
    prometheus_data:
    grafana_data: