global:
  scrape_interval: 15s # Seberapa sering mengambil data dari target
  evaluation_interval: 15s

scrape_configs:
  - job_name: "neopark_server"
    # Gunakan nama service Docker sebagai hostname
    static_configs:
      - targets: ["neopark-server:5000"] # Menggunakan nama service Docker, bukan localhost
    metrics_path: "/metrics" # Pastikan endpoint metrics tersedia
    scrape_interval: 15s
    scrape_timeout: 10s
