name: NeoPark Server CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_lint_and_test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.9"]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Create dummy model file for test collection
              run: |
                  echo "This is a dummy YOLO model file for PyTest collection." > fine-best.pt
                  echo "Created dummy fine-best.pt in $(pwd)"
                  ls -l fine-best.pt

            - name: Lint with flake8
              run: |
                  flake8 Server/ tests/

            - name: Run tests with pytest
              run: |
                  pytest -v tests/

            - name: Build Docker image
              if: success()
              run: |
                  docker build . --file Dockerfile --tag neopark-server-ci:$(date +%s)
